pipeline {
  agent any
  parameters {
	}
  stages {
    stage('Artifactory Pull') {
	  	steps {
		  	sh 'echo "*************************GitHub Pull*************************"'
		  }	
	  }
  	stage('Transfer to Target Server') {
  		steps {
			  sh 'echo "*************************Sonar Testing*************************"'
 		  }	
	  }
				stage('UnTar Package') {
	  	steps {
		  	sh 'echo "*************************Build/Tar Package*************************"'
		  }	
	  }
  	stage('Smoke Test') {
  		steps {
			  sh 'echo "*************************Artifactory Load*************************"'
 		  }	
	  }
	  }
  post {
    failure {
        mail to: 'email address',
             subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
             body: "Something is wrong with ${env.JOB_URL}"
  }
}
