### set vagrant version
VAGRANTFILE_API_VERSION = "2"

Vagrant::configure(VAGRANTFILE_API_VERSION) do |global_config|
#  global_config.vbguest.iso_path = "/home/p/VBoxGuestAdditions_4.3.18.iso"
#  global_config.vbguest.auto_update = false

  #use hostmanager plugin to configure /etc/hosts on host and guest
  global_config.hostmanager.enabled = true

  #begin guest definition
  global_config.vm.define("jenkins.internal.tld") do |config|

    # use ubuntu bento box
    config.vm.box = "ubuntu/xenial64"

    # use hostmanager plugin to configure /etc/hosts
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

    #configure private non-NAT interface
    config.vm.network :private_network, ip: "10.0.1.201"
    config.vm.hostname = "jenkins.internal.tld"

    #set virtual providor
    config.vm.provider "virtualbox" do |v|
        v.linked_clone = true
    end


    # bootstrap
    config.vm.provision "shell",
      inline: "apt-get -y install python"

    # provision
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "site.yml"
    end

  end

  global_config.vm.define("web.internal.tld") do |config|

    # use ubuntu bento box
    config.vm.box = "ubuntu/xenial64"

    # use hostmanager plugin to configure /etc/hosts
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

    #configure private non-NAT interface
    config.vm.network :private_network, ip: "10.0.1.202"
    config.vm.hostname = "web.internal.tld"

    #set virtual providor
    config.vm.provider "virtualbox" do |v|
        v.linked_clone = true
    end


    # bootstrap
    config.vm.provision "shell",
      inline: "apt-get -y install python"

    # provision
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "site.yml"
    end

  end

  global_config.vm.define("api.internal.tld") do |config|

    # use ubuntu bento box
    config.vm.box = "ubuntu/xenial64"

    # use hostmanager plugin to configure /etc/hosts
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

    #configure private non-NAT interface
    config.vm.network :private_network, ip: "10.0.1.203"
    config.vm.hostname = "api.internal.tld"

    #set virtual providor
    config.vm.provider "virtualbox" do |v|
        v.linked_clone = true
    end


    # bootstrap
    config.vm.provision "shell",
      inline: "apt-get -y install python"

    # provision
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "site.yml"
    end

  end

end
