pipeline {
  agent any
  stages {
    stage('GitHub Pull') {
	  	steps {
		  	sh 'echo "*************************GitHub Pull*************************"'
        script {
          checkout([$class: 'GitSCM',
            branches: [[name: '*/master']],
            doGenerateSubmoduleConfigurations: false,
            extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: "rlennon/doodle/src/infra/ansible"]],
            submoduleCfg: [],
            userRemoteConfigs: [[url: 'git@github.com:rlennon/doodle']]
          ])
        }
			}
	  }
    stage('Ansible linting') {
    	steps {
      	  sh 'echo "*************************Ansible Linting*************************"'
          sh 'cd ${WORKSPACE}/src/infra/ansible'
          sh 'ansible-lint *.yml'
    	  }
    }
    stage('Ansible Prevision: staging') {
      steps {
        sh 'echo "*************************Ansible Provision: Staging*************************"'
        sh 'ansible-playbook -i ${WORKSPACE}/src/infra/ansible/hosts-staging.ini ${WORKSPACE}/src/infra/ansible/site.yml'
      }
    }
  }
}
