pipeline {
  agent any
  parameters {
	  string(defaultValue: '', description: '', name: 'DOODLE_BUILD_JOB_BUILD_NUMBER')
	}
  stages {
    stage('GitHub Pull') {
	  	steps {
		  	sh 'echo "*************************GitHub Pull*************************"'
        script {
          checkout([$class: 'GitSCM',
            branches: [[name: '*/master']],
            doGenerateSubmoduleConfigurations: false,
            extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: "rlennon/doodle/src/infra/ansible"]],
            submoduleCfg: [],
            userRemoteConfigs: [[url: 'git@github.com:rlennon/doodle']]
          ])
        }
			}
	  }
    stage('Ansible linting') {
    	steps {
      	  sh 'echo "*************************Ansible Linting*************************"'
          sh 'ansible-lint ${WORKSPACE}/src/infra/ansible/site.yml'
    	  }
    }
    stage('Ansible Provision: staging') {
      steps {
        sh 'echo "*************************Ansible Provision: Staging*************************"'
        sh 'ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook --tags=provision -u doodle -i ~/hosts-staging.ini ${WORKSPACE}/src/infra/ansible/site.yml'
      }
    }
  }
  post {
		success {
			build job: 'Deploy_Staging', parameters: [string(name: 'DOODLE_BUILD_JOB_BUILD_NUMBER', value: "${BUILD_NUMBER}")], wait: false
		}
    always {
      cleanWs()
    }
  }
}
