pipeline {
  agent any
	parameters {
			  string(defaultValue: '', description: '', name: 'DOODLE_BUILD_JOB_BUILD_NUMBER')
	}	
  stages {
    stage('Artifactory Pull') {
	  	steps {
		  	sh '''
					echo "*************************Artifactory Pull*************************"
					curl -u ${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} "${ARTIFACTORY_SERVER}:${ARTIFACTORY_PORT}/artifactory/doodle-release-local/com/doodle/build/doodle_build-${DOODLE_BUILD_JOB_BUILD_NUMBER}/doodle_build-${DOODLE_BUILD_JOB_BUILD_NUMBER}.tar" -o ${WORKSPACE}/doodle_build-${DOODLE_BUILD_JOB_BUILD_NUMBER}.tar
				  ls -ltr
				'''
		  }	
	  }
		stage('Test connection to Staging API Server') {
  		steps {
			  sh 'echo "*************************Transfer to Target Server*************************"'
				sshPublisher(publishers: [sshPublisherDesc(configName: 'Doodle-API-Staging', transfers: [sshTransfer(cleanRemote: false, 
						excludes: '', 
						execCommand: '''
													cd /home/doodle/Doodle/src/
													ls -ltr
													''', 
						execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', 
						remoteDirectory: '', remoteDirectorySDF: false, removePrefix: '', 
						sourceFiles: '')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
 		  }	
		}
		stage('Test connection to Staging UI Server') {
  		steps {
			  sh 'echo "*************************Transfer to Target Server*************************"'
				sshPublisher(publishers: [sshPublisherDesc(configName: 'Doodle-UI-Staging', transfers: [sshTransfer(cleanRemote: false, 
						excludes: '', 
						execCommand: '''
													cd /home/doodle/Doodle/src/
													ls -ltr
													''', 
						execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', 
						remoteDirectory: '', remoteDirectorySDF: false, removePrefix: '', 
						sourceFiles: '')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
 		  }	
		}
  	stage('Deployment Validation Test') {
  		steps {
			  sh 'echo "*************************Smoke Test*************************"'
 		  }	
	  }
    stage('Security Scanning') {
	  	steps {
		  	sh '''
			  echo "*************************Running Security scan for open ports*************************"
			  if [ -n "${WORKSPACE:+1}" ]; then
    		 	# Path to virtualenv cmd installed by pip
    			# /usr/local/bin/virtualenv
    			PATH=$WORKSPACE/venv/bin:/usr/local/bin:$PATH
    			if [ ! -d "venv" ]; then
            	    virtualenv -p python3 venv
    			fi
    			    . venv/bin/activate
			  fi
			  python3 ./vars/Staging_security_port_scanning.py
		    '''  		  
			}
		}	
	post {
		success {
			build job: 'Deploy_Production', parameters: [string(name: 'DOODLE_BUILD_JOB_BUILD_NUMBER', value: "${BUILD_NUMBER}")], wait: false
		}	
		always {
			cleanWs() 
		}
	}
}
